# Generated by Django 3.2.8 on 2021-11-07 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.imageproduct'),
        ),
    ]
