# Generated by Django 3.2.8 on 2021-11-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_remove_customer_cart'),
        ('shop', '0003_auto_20211107_0652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='ImageProduct',
        ),
    ]
