# Generated by Django 3.2.8 on 2021-11-08 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20211107_0719'),
        ('authorization', '0002_remove_customer_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.item')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='cart_user',
            field=models.ManyToManyField(through='authorization.CartCustomer', to='shop.Item'),
        ),
    ]
